export const metadata = {
  title: "Zod validation form",
  description: "Generated by Zod validation form",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div>{children}</div>;
}
